import test from "node:test";import assert from "node:assert/strict";
import { buildBatchB4AsanteSanaApplySql,buildBatchB4AsanteSanaRollbackSql,compileBatchB4AsanteSana } from "../lib/phase5f-batch-b4-asante-sana.mjs";
const d=compileBatchB4AsanteSana();
test("B4 compiles the exact 81-row ASANTE SANA manifest subset",()=>{assert.deepEqual([d.providers.length,d.providerSources.length,d.providerOrganizations.length,d.offerings.length,d.offeringSources.length,d.identityLinks.length,d.designations.length,d.batch.netNewRows],[10,10,21,10,10,10,10,81]);assert.equal(d.providers.at(-1).name,"CMS Pays-d’Enhaut");});
test("nine ordinary CMS use ASANTE SANA operator and AVASAD network",()=>{for(const p of d.providers.slice(0,9))assert.deepEqual(d.providerOrganizations.filter((x)=>x.provider_id===p.id).map((x)=>[x.organization_slug,x.relationship_type,x.is_primary]),[["asante-sana","operator",true],["avasad","network",false]]);});
test("Pays-d’Enhaut uses Pôle Santé operator and two networks",()=>{const p=d.providers.at(-1);assert.deepEqual(d.providerOrganizations.filter((x)=>x.provider_id===p.id).map((x)=>[x.organization_slug,x.relationship_type,x.is_primary]),[["pole-sante-pays-denhaut","operator",true],["asante-sana","network",false],["avasad","network",false]]);});
test("B4 stays minimal, unpublished, unverified, and location-free",()=>{assert.ok(d.providers.every((x)=>!x.is_published&&x.verification_status==="unverified"&&x.locality===null&&x.service_codes.length===0&&x.language_codes.length===0));assert.ok(d.offerings.every((x)=>x.offering_type==="home_care"&&!x.is_published));assert.ok(d.designations.every((x)=>x.designation_status===null&&x.effective_on===null&&x.issuing_organization_id===null&&!x.is_published));});
test("B4 SQL requires the isolated prerequisite and creates no enrichment",()=>{const sql=buildBatchB4AsanteSanaApplySql({rollback:true});assert.match(sql,/providers\)<>86/);assert.match(sql,/pole-sante-pays-denhaut/);assert.match(sql,/ROLLBACK;\s*$/);assert.doesNotMatch(sql,/INSERT INTO public\.(provider_service_areas|care_offering_features|care_offering_availability)/);});
test("B4 rollback deletes deterministic rows in reverse dependency order",()=>{const sql=buildBatchB4AsanteSanaRollbackSql(),order=["care_offering_regulatory_designations","provider_identity_links","care_offering_sources","care_offerings","provider_organizations","provider_sources","providers"];for(let i=1;i<order.length;i++)assert.ok(sql.indexOf(`DELETE FROM public.${order[i-1]}`)<sql.indexOf(`DELETE FROM public.${order[i]}`));});
